/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  IsOptional,
  IsEnum,
  IsDate,
  IsString,
  ValidateNested,
} from "class-validator";
import { EnumTravelCategory } from "./EnumTravelCategory";
import { Type } from "class-transformer";
import { TicketUpdateManyWithoutTravelsInput } from "./TicketUpdateManyWithoutTravelsInput";
import { VehicleWhereUniqueInput } from "../../vehicle/base/VehicleWhereUniqueInput";

@InputType()
class TravelUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  basePrice?: number;

  @ApiProperty({
    required: false,
    enum: EnumTravelCategory,
  })
  @IsEnum(EnumTravelCategory)
  @IsOptional()
  @Field(() => EnumTravelCategory, {
    nullable: true,
  })
  category?: "Bus" | "Train" | "Airplane" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  destination?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  discount?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  source?: string;

  @ApiProperty({
    required: false,
    type: () => TicketUpdateManyWithoutTravelsInput,
  })
  @ValidateNested()
  @Type(() => TicketUpdateManyWithoutTravelsInput)
  @IsOptional()
  @Field(() => TicketUpdateManyWithoutTravelsInput, {
    nullable: true,
  })
  ticketId?: TicketUpdateManyWithoutTravelsInput;

  @ApiProperty({
    required: false,
    type: () => VehicleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VehicleWhereUniqueInput)
  @IsOptional()
  @Field(() => VehicleWhereUniqueInput, {
    nullable: true,
  })
  vehicleId?: VehicleWhereUniqueInput | null;
}

export { TravelUpdateInput as TravelUpdateInput };
