/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsEnum,
  IsOptional,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { EnumTicketGender } from "./EnumTicketGender";
import { TravelWhereUniqueInput } from "../../travel/base/TravelWhereUniqueInput";
import { Type } from "class-transformer";
import { UserTicketWhereUniqueInput } from "../../userTicket/base/UserTicketWhereUniqueInput";

@InputType()
class TicketCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  firstName!: string;

  @ApiProperty({
    required: true,
    enum: EnumTicketGender,
  })
  @IsEnum(EnumTicketGender)
  @Field(() => EnumTicketGender)
  gender!: "Male" | "Female";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  lastName!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  nationalId!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  seatNumber!: number;

  @ApiProperty({
    required: false,
    type: () => TravelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TravelWhereUniqueInput)
  @IsOptional()
  @Field(() => TravelWhereUniqueInput, {
    nullable: true,
  })
  travelId?: TravelWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserTicketWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserTicketWhereUniqueInput)
  @IsOptional()
  @Field(() => UserTicketWhereUniqueInput, {
    nullable: true,
  })
  userId?: UserTicketWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  vehicleId!: number;
}

export { TicketCreateInput as TicketCreateInput };
