/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VehicleService } from "../vehicle.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VehicleCreateInput } from "./VehicleCreateInput";
import { VehicleWhereInput } from "./VehicleWhereInput";
import { VehicleWhereUniqueInput } from "./VehicleWhereUniqueInput";
import { VehicleFindManyArgs } from "./VehicleFindManyArgs";
import { VehicleUpdateInput } from "./VehicleUpdateInput";
import { Vehicle } from "./Vehicle";
import { SeatFindManyArgs } from "../../seat/base/SeatFindManyArgs";
import { Seat } from "../../seat/base/Seat";
import { SeatWhereUniqueInput } from "../../seat/base/SeatWhereUniqueInput";
import { TravelFindManyArgs } from "../../travel/base/TravelFindManyArgs";
import { Travel } from "../../travel/base/Travel";
import { TravelWhereUniqueInput } from "../../travel/base/TravelWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VehicleControllerBase {
  constructor(
    protected readonly service: VehicleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Vehicle })
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: VehicleCreateInput): Promise<Vehicle> {
    return await this.service.create({
      data: data,
      select: {
        category: true,
        color: true,
        corporation: true,
        createdAt: true,
        id: true,
        numberOfSeats: true,
        numberPlate: true,
        ownerNationalId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Vehicle] })
  @ApiNestedQuery(VehicleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Vehicle[]> {
    const args = plainToClass(VehicleFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        category: true,
        color: true,
        corporation: true,
        createdAt: true,
        id: true,
        numberOfSeats: true,
        numberPlate: true,
        ownerNationalId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Vehicle | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        category: true,
        color: true,
        corporation: true,
        createdAt: true,
        id: true,
        numberOfSeats: true,
        numberPlate: true,
        ownerNationalId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() data: VehicleUpdateInput
  ): Promise<Vehicle | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          category: true,
          color: true,
          corporation: true,
          createdAt: true,
          id: true,
          numberOfSeats: true,
          numberPlate: true,
          ownerNationalId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Vehicle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Vehicle | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          category: true,
          color: true,
          corporation: true,
          createdAt: true,
          id: true,
          numberOfSeats: true,
          numberPlate: true,
          ownerNationalId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/seats")
  @ApiNestedQuery(SeatFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Seat",
    action: "read",
    possession: "any",
  })
  async findManySeats(
    @common.Req() request: Request,
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Seat[]> {
    const query = plainToClass(SeatFindManyArgs, request.query);
    const results = await this.service.findSeats(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        isReserved: true,
        seatNumber: true,
        updatedAt: true,

        vehicleId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/seats")
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  async connectSeats(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: SeatWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seats: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/seats")
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  async updateSeats(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: SeatWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seats: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/seats")
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  async disconnectSeats(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: SeatWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seats: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/travelId")
  @ApiNestedQuery(TravelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Travel",
    action: "read",
    possession: "any",
  })
  async findManyTravelId(
    @common.Req() request: Request,
    @common.Param() params: VehicleWhereUniqueInput
  ): Promise<Travel[]> {
    const query = plainToClass(TravelFindManyArgs, request.query);
    const results = await this.service.findTravelId(params.id, {
      ...query,
      select: {
        basePrice: true,
        category: true,
        createdAt: true,
        date: true,
        destination: true,
        discount: true,
        id: true,
        source: true,
        updatedAt: true,

        vehicleId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/travelId")
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  async connectTravelId(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: TravelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      travelId: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/travelId")
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  async updateTravelId(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: TravelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      travelId: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/travelId")
  @nestAccessControl.UseRoles({
    resource: "Vehicle",
    action: "update",
    possession: "any",
  })
  async disconnectTravelId(
    @common.Param() params: VehicleWhereUniqueInput,
    @common.Body() body: TravelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      travelId: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
