/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumVehicleCategory } from "./EnumVehicleCategory";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { SeatListRelationFilter } from "../../seat/base/SeatListRelationFilter";
import { TravelListRelationFilter } from "../../travel/base/TravelListRelationFilter";

@InputType()
class VehicleWhereInput {
  @ApiProperty({
    required: false,
    enum: EnumVehicleCategory,
  })
  @IsEnum(EnumVehicleCategory)
  @IsOptional()
  @Field(() => EnumVehicleCategory, {
    nullable: true,
  })
  category?: "Bus" | "Train" | "Airplaine";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  color?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  corporation?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  numberOfSeats?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  numberPlate?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  ownerNationalId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SeatListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SeatListRelationFilter)
  @IsOptional()
  @Field(() => SeatListRelationFilter, {
    nullable: true,
  })
  seats?: SeatListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TravelListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TravelListRelationFilter)
  @IsOptional()
  @Field(() => TravelListRelationFilter, {
    nullable: true,
  })
  travelId?: TravelListRelationFilter;
}

export { VehicleWhereInput as VehicleWhereInput };
